### ISSUE TITLE
Bon Drucker

### ISSUE THREAD

**Issue by btvj** [btkpfw/201611#118]
der Bon Drucker funkitioniert seid dem 04.12.17 gegen 16 Uhr nicht mehr

**Comment by btkpfw** [comment]
... und nich mal 20 Min nach dem Issue   sollte es gefixt sein ;))

**Comment by btkpfw** [comment]
Problemanalyse:

User "ks" hat am 4.12.17 um 15:37:47 die Datei "ChkLst_ks.pdf" an den Drucker gesendet.

Das löst diesen Fehler aus!!

Bitte Arbeitsabläufe nochmals überprüfen.
