### ISSUE TITLE
Opel Kommunikation

### ISSUE THREAD

**Issue by btvj** [btkpfw/201611#13]
viele offen Baustellen

Kampagnenabfrage zu Opel
Opel Teilebestellung
RIM ??
Garantieanträge und Kulanzen senden

hoffentlich mit dem Termin mit Herren Mund am Montag erledigt

**Comment by btkpfw** [comment]
Bearbeitung durch attribut

**Comment by btkpfw** [comment]
Bearbeitung durch Herrn Schöne
am 30.11. ok
am 1.12. Fehleranalyse durch H.Schöne: GatewayVPN down

**Comment by btkpfw** [comment]
Gateway-VPN up

lt H.Schöne sollte jetzt funktionieren.

noch zu klären Issue #27

**Comment by btkpfw** [comment]
#27 erledigt

getestet und funktioniert solange Terminal-Gateway-VPN online
