### ISSUE TITLE
Update einspielen

### ISSUE THREAD

**Issue by btvj** [btkpfw/201611#137]
ich habe dir am 10.07. eine Mail (bzw 2) geschickt, da soll ein WICHTIGES Update für MPNEW eingespielt werden.

Bitte erledige das umgehend. 

Datensicherung wäre auch mal nicht schlecht!!! Oder hattest du eine gemacht, wo wir drüber gesprochen haben?

**Comment by btkpfw** [comment]
hat Attribut erledigt
