### ISSUE TITLE
Drucken aus den Ubuntu Rechnern

### ISSUE THREAD

**Issue by btvj** [btkpfw/201611#138]
Richte bitte ein, das man auch Rechnungen (aus Station 10) von den Ubuntu Rechnern drucken kann!

Besser oder fantastisch wäre ja wenn es wieder automatisch geht wenn ich wieder komme. 
Das wäre wie ein Wunder

**Comment by btkpfw** [comment]
Das funktionierte schon seit einem Jahr; wußte leider nur keiner ?;))

Problem wurde ende August durch Schulung gelöst.
