### ISSUE TITLE
Sammel Issue

### ISSUE THREAD

**Issue by btvj** [btkpfw/201611#140]
Wenn ich nicht da bin, hast du eigentlich sehr viel zu tun. , TeamViewer, StarMoney, Update , Drucken am besten automatisch,

**Comment by btkpfw** [comment]
Sammel Issues machen keinen sinn! außerdem haben wir das alles schon mal einzeln.

Wenn Du die "alten" issues in erinnerung bringen möchtest, dann einfach noch mal einen kommentar dazu schreiben.

Das hat den sinn, dass bei mir kürzlich kommentierte issues höher in der liste angezeigt werden.

Gruss
