### ISSUE TITLE
Rechnung per Mail

### ISSUE THREAD

**Issue by btvj** [btkpfw/201611#15]
Erklärungsbedaf Rg per pdf speichern und per Mail verschicken

**Comment by btkpfw** [comment]
Alle Rechnungen sind als pdf auf dem Drucker-Laufwerk (P:) zu finden.

Die ensprechende Rechnung mit rechts anclicken und "Senden an... -> e-mail Empfänger".

Vorraussetzung e-mail-Versand ist unter dem localen Windows eingerichtet.
