### ISSUE TITLE
TIS Verbindung

### ISSUE THREAD

**Issue by btvj** [btkpfw/201611#29]
Im MP-New läßt sich kein Serviceplan drucken, keine Tis Verbindung meint der PC

**Comment by btkpfw** [comment]
Terminal-Gateway VPN offline

**Comment by btkpfw** [comment]
Rückruf von Att

TIS-Integration noch nicht Installiert,

Att hat aber jetzt Feierabend.

Ich Übernehme obwohl nich meine Aufgabe ;-)

**Comment by btkpfw** [comment]
Zugriff auf LT-Tab im TIS nicht möglich

Rechte-Problem ??

**Comment by btkpfw** [comment]
DMS-Integration Installiert

ActiveX Steuerelemente über GPO freigegeben
