### ISSUE TITLE
Meisterbüro Kfz-Pilot

### ISSUE THREAD

**Issue by btvj** [btkpfw/201611#31]
im Meisterbüro einrichten inkl. TIS und EPC Intergration 
Internetbox mit Service-Mails einrichten
Drucken auf Annahme Drucker

**Comment by btkpfw** [comment]
Bearbeitung nicht möglich da PC in Benutzung

**Comment by btkpfw** [comment]
manueller neustart notwendig

**Comment by btvj** [comment]
Warum rufst du nicht mal im AH aus und sagst es soll jemand neu starten und wenn jemand dran ist dann gibt Zeichen und sage du machst gerade was.

**Comment by btkpfw** [comment]
... weil um 21.00 Uhr keiner ans Telefon geht !!!

**Comment by btkpfw** [comment]
erst #43 lösen dann wird auch dieses issue gelöst sein

**Comment by btkpfw** [comment]
#43 provisorisch gelöst; damit sollte auch das funktionieren!

Test aktuell nicht möglich, da PC down.

bleibt "in Arbeit",mindestens, bis zum Test

**Comment by btvj** [comment]
Rechner geht nicht , schade

**Comment by btkpfw** [comment]
LZO-comp für VPN-Link war disabled
