### ISSUE TITLE
Annahme PC

### ISSUE THREAD

**Issue by btvj** [btkpfw/201611#32]
Bitte stelle dort wieder einen hin, da sonst drucken aus der Werkstatt ein umständliches Problem ist,

An den meisten Druckern kommen nur komische Seiten raus, welche ich nicht lesen kann.
Kopierer geht,  aber der Weg ist sehr weit.

**Comment by btkpfw** [comment]
Der PC war eigendlich für #17 gedacht aber nach (vorläufiger)Fertigstellung von #43 hier jetzt wichtiger

**Comment by btkpfw** [comment]
PC angeschlossen

Drucker Anbindung noch offen

**Comment by btkpfw** [comment]
Weitere Aufgabe aus #55:

TIS via Firefox mit allen Plugins

**Comment by btkpfw** [comment]
Zum testen aktuell an Station-15
