### ISSUE TITLE
MP-new

### ISSUE THREAD

**Issue by btvj** [btkpfw/201611#40]
Montag früh und es geht schon wieder kein Mp-new und keine GWM Abfrage, was ist los????

**Comment by btkpfw** [comment]
Fehler bei der DNS-Auflösung

Haupt- Fehler: #39 

Seit 14:00 Gelöst

**Comment by btvj** [comment]
Problem ist heute früh wieder da, an Station 10 geht es wieder niccht

**Comment by btkpfw** [comment]
um 10:00 durch neustart des Gateway-VPN vorrübergehend beseitigt

**Comment by btkpfw** [comment]
bis zur erledigung #42 : workaround: Neustart GatewayVPN um 2:00 Uhr

**Comment by btkpfw** [comment]
Funktioniert bis jetzt!!

nach #43 Lösung mal schauen ob das Problen auch so Gelöst ist;

Sonst ist auch Zukünftige Lösung von #43 vielleicht die Lösung für dieses Issue
