### ISSUE TITLE
office Paket 

### ISSUE THREAD

**Issue by btvj** [btkpfw/201611#49]
neues bereits vorhandenes office Paket auf Server einspielen

**Comment by btkpfw** [comment]
Warum?? Bitte auswählen

- damit der Admin was zu tun hat
- es ist zuviel Festpattenspeicher frei
- der Server arbeitet zu schnell
- wir müssen Rechenleistung des Servers binden
- KfzPilot läuft zu problemlos 
- wir brauchen VB-Scripting(Macros) um Schadsoftware zu installieren
- ohne Office können wir keine Sicherheitslücken im Office mittels Office-Updates beheben
- ...
... oder habe ich einen Grund übersehen

**Comment by btvj** [comment]
Ach übrigens: es war dein Vorschlag es auf dem Server zu installieren, 
Ich brauche es für das Datev zu senden der Lohndaten jedoch verschicke ich diese von meinem PC. 
Weiterhin möchte ich gern die Attribut Selektion mit Excel tun, auch wenn dir das nicht gefällt

**Comment by btkpfw** [comment]
Ja, wenn wir es brauchen, dann ok aber:

Für Lohn nicht auf dem Server nötig --> richtig

KPfW erzeugt doch bei der Selektion auch eine Datei, welche dann local geöffnet werden muß ??

**Comment by btkpfw** [comment]
bisher keine Notwendigkeit für eine Serverinstallation.

Wenn es einen Anwendungsfall giebt, dieses Issue bitte reopen
