### ISSUE TITLE
Timeout Benutzerwechsel

### ISSUE THREAD

**Issue by btvj** [btkpfw/201611#5]
wenn ich auf einen Auftrag arbeite und der PC sich abmeldet ist der Auftrag gesperrt, Meldet sich Andrea dann an ist der Auftrag für das ganze AH gesperrt , nur ich kann ihn wieder entsperren.

**Comment by btkpfw** [comment]
Problem-Erklärung:
Nach aktuellem Stand der Datenbanktechnologie ist es nicht möglich, dass nehrere Nutzer den selben Datensatz bearbeiten. Daher hat die Fa. attribut das Konzept der gesperrten Datensätze von Microsoft Access übernommen. In Kombination mit Issue #4 (immer wieder von vorne anfangen) ist es möglich nach einem serneiten User-Login an der "gleichen Stelle" weiter zu machen. Diese Funktionalität nutzen wir schon seit längerem im "Internet-Terminal". Das Internwt-Terminal basiert jedoch vollständig auf freier Software. Windows und KfPW beinhaltet jedoch sehr restrictive Lizensvereinbarungen. Daher ergibt sich die folgende:

# **Bedenkensanmeldung**

Sollte der Nutzer 15 minuten nichts am PC machen, wird die Verbindung zum Server getrennt. Durch das Offen lassen der aktuellen User-Session ( Wunsch aus Issue  #4 ) ist es nicht mehr notwendig, die 20Sekunden Arbeitszeit dafür aufzuwenden, wieder an die Stelle der abgebrochenen Session zu gelangen. 

**Hiermit_ sollen die Bedenken dokumentiert werden, dass diese von btvj geforderte Praxis einen unverhältnismäßigen Mehrverbrauch an User-Lizenzen erfordert. **

### Erklärung:
Wird eine Verbindung getrennt, unabhängig ob duch Verbindungsunterbrechung oder durch 15min Timeout, bleibt die User-Session (und damit die Lizens) ewig aktiv. Dies führt über kurz oder lang, zum Verbrauch aller Lizenzen. Um die Lizenzen wieder frei zu geben, ist vermutlich ein Neustart des Servers notwendig. Das wird die Firma aber mindestens 20 MINUTEN!! Down-Time kosten.

# Die gewünschte Funktion ist trotz der Dedenken ab sofort aktiviert!!!

**Weitere Aktionen:** 

Wenn innerhalb von 24h keine weiteren Einträge erfolgen, wird dieses Issue ,mit zusätzlichem Arbeitsaufwand, rückgängig gemacht.

Wenn btvj dieses Issue schließt, bleibt die Konfiguration trotz erheblicher, technischer Bedenken bestehen.

**Comment by btkpfw** [comment]
Nach Problemen mit abgemeldeten Sitzungen umgestellt auf "Abmelden bei trennen"
