### ISSUE TITLE
Zugangsdaten neuer Server

### ISSUE THREAD

**Issue by btvj** [btkpfw/201611#53]
Um die Rechnungen herunterzuladen brauche ich Zugansdaten, aber die Firma gibt mit keine Auskunft
Bitte kümmere dich , das ich die Rechnungen per Mail erhalte

**Comment by btkpfw** [comment]
Versand von e-mail-Rechnungen kann erst nach Bestätigung der e-Mail konfiguriert werden.

Bitte Bestätigungs-Mail beantworten.

**Comment by btvj** [comment]
Mail bestätigt. :) Danke 

Bekomme ich die alten auch noch oder muss ich da noch mal anrufen oder schreiben?????

**Comment by btkpfw** [comment]
Die e-Mail-Bestätigung war der 1. Schritt.

Jetzt noch mal den Rechnungs-empfang bestätigen.

Die alten Rechnungen liegen im Ordner Rechnungen auf dem Drucker-Laufwerk
