### ISSUE TITLE
Internetbox 

### ISSUE THREAD

**Issue by btvj** [btkpfw/201611#59]
Wie bekomme ich die E-Mail Anhänge in mein "normales System" zur weiteren Bearbeitung??????????????????????????????????????????????????????????

**Comment by btkpfw** [comment]
Alle Anhänge Pauschal ?

Gar NICHT!

Was spricht gegen eine Bearbeitung in der Internetbox? 
... und was ist ein "normales System"  ?
    * das lokale WindowsXp welches abgeschafft werden soll ?
    * das Windows auf dem Remote Desktop Server ?
    * das lokale Linux ?

Im Einzelfall z.B. Lohndaten siehe #18 

Bitte für ein konkretes Problen ein eigenes ISSUE, dann kann das auch konkret bearbeitet werden.

Eine pauschallösung wird zu Aufwändig
