### ISSUE TITLE
Chef Heimarbeitsplatz 

### ISSUE THREAD

**Issue by btvj** [btkpfw/201611#61]
Chef möchte  Heimarbeitsplatz.

**Comment by btkpfw** [comment]
ToDo 

Datensicherung:
md5 über die HDD: 
sda als tar.gz sichern
tar.gz mit md5 testen

Install lubuntu als Vbox
Install lubuntu als dualboot
Install lubuntu auf USB-Stick

**Comment by btkpfw** [comment]
eb720825b9399062912d6752b19cc46b6 *

**Comment by btkpfw** [comment]
Drucker eingerichtet
