### ISSUE TITLE
Mitarbeiter für Stempeluhr

### ISSUE THREAD

**Issue by btvj** [btkpfw/201611#62]
Mitarbeiter für Stempeluhrzugang

PL, KS, JK, RF, JN,KK

**Comment by btkpfw** [comment]
Initial-Passwort ist: 2017@TerminalServer2012

Das Passwort muß bei der ersten Anmeldung geändert werden

Bitte testen und dann ISSUE bitte schließen

**Comment by btvj** [comment]
alle MA angelegt und ausprobiert
