### ISSUE TITLE
EPC KPfW-Integration

### ISSUE THREAD

**Issue by btkpfw** [btkpfw/201611#66]
Verbindung zu GM geprüft,

'Webseite spoepc.xw.gm.com ist als "vertrauenswürdig" eingestuft.

Dennoch ist der Service nicht verfügbar.

Da muß mal Attribut draufschauen.

**Comment by btvj** [comment]
:)

**Comment by btvj** [comment]
Ich habe was für dich:)
[attRiBut Opel EPC5 Anbindung.pdf](https://github.com/btkpfw/201611/files/699035/attRiBut.Opel.EPC5.Anbindung.pdf)
[attRiBut Opel EPC5 Anbindung kurz.pdf](https://github.com/btkpfw/201611/files/699037/attRiBut.Opel.EPC5.Anbindung.kurz.pdf)

**Comment by btkpfw** [comment]
Die Anleitung funktioniert (wie immer) NICHT!

Win2012 kann kein Flash OOTB.

Der Parameter EPC3Launch wird nicht korrekt an den IE weitergeleitet !

Bin ich der erste der die EPC-Integration installiert ?? :confused:

**Comment by btkpfw** [comment]
Flash-Problem gelöst
neues Problem :  :worried:
  KPfW logt sich nicht ein

**Comment by btkpfw** [comment]
Integrations-Assisaten braucht Java 1.7+ Installiert ist nach Weisung Herr Schöne 1.8 das geht aber nicht! (warum auch immer)

Ich habe keine lust mehr Attribut Ihren Problemen hinterherzulaufen, wenn wir nicht vorher über Geld geredet haben!!

Mein Vorschlag 500€ Erfolgspremie! 
(Bei Abrechnung nach Zeit laufen sonst die Kosten völlig aus dem Ruder)

Somit bis auf weiteres Problemlösung abgebrochen!!

**Comment by btkpfw** [comment]
Nur der Vollständigkeit halber:

im Anhang das Grundproblem, welches bis jetzt immer noch nicht gelöst ist!! 

Das ist nicht das Java-Problem!

![epc5-problem](https://cloud.githubusercontent.com/assets/23710462/22152169/d034900e-df21-11e6-8ef8-cf76d791cb2e.jpg)

 Vermutlich muß da gar kein Java neu installiert werden, wenn Att erstmal die Probleme in Ihrer eigenen Software löst.
