### ISSUE TITLE
Arbeitsverweigerung durch Attribut

### ISSUE THREAD

**Issue by btkpfw** [btkpfw/201611#74]
Herr J.

macht nichts meha am Server weil:

(Bitte korrekte Gründe nachtragen)

drss informiert durch vj am 20.1.17 um 09:42

Attribut (Frau D.Sein) verspricht um 09:51 umgehenden Rückruf

**Comment by btvj** [comment]
????

**Comment by btvj** [comment]
Schreiben mit DR zusammen beantwortet
