### ISSUE TITLE
EPC

### ISSUE THREAD

**Issue by btvj** [btkpfw/201611#9]
EPC New einrichten  im Lager und am Tresen ( andere Systemvoraussetzungen )

**Comment by btkpfw** [comment]
Ist EPC New nicht nur Internetexplorer?
Welche andere Systemvoraussetzungen?

**Comment by btvj** [comment]
Ja aber unsere Rechner besitzen dies Voraussetzungen nicht ( es war Windows 7 und anderer Explorer)

**Comment by btkpfw** [comment]
Mit Firefox auf den Linux-Systemen funktioniert
