### ISSUE TITLE
große Druck Probleme

### ISSUE THREAD

**Issue by btvj** [btkpfw/201611#92]
seid dem die Drucker nicht mehr angeschlossen sind, gibt es sehr große Zeitverzögerungen beim drucken (7min) Druck kommt schnell raus, aber die Verarbeitungszeit danach ist extrem

**Comment by btvj** [comment]
Die extereme Wartezeit aus dem Attribut ist weg, jedoch die vielen Umwege bis zum Druckauftrag fertig sind nicht schön..
Wir möchten wieder mit einen Klick den Druckauftrag haben :)

**Comment by btkpfw** [comment]
Die Probleme sind nich größer als bisher auch.

Gelöst duch neues Drucksystem
