### ISSUE TITLE
Anmeldung an Kasse

### ISSUE THREAD

**Issue by btvj** [btkpfw/201611#99]
Am Kassen PC muß man sich 3-4 mal anmelden, ehe das Feld kommt Passwort eingeben.

**Comment by btkpfw** [comment]
Änderungen am Anmeldesysten des W2012 erzeugen den Effekt. Rücksetzen auf Standart-Anmeldetiming habe ich schon in 12-2016 empfolen.

Bitte dafür extra Issue.
